### ISSUE TITLE
using cache

### ISSUE THREAD

**Issue by FrancisVarga** [aequasi/memcached-bundle#3]
i using your config for session and caching doctrine layer. My problem is it never hit some attributes and never write. Maybe the config is wrong?

Memcached is running:

```
$ ps ax | grep memc
57980   ??  Ss     0:00.02 memcached -m 512 -p 11211 -d
```

Another problem is also i can't use the console tool:

```
app/console memcached:set key value lifetime=60
cluster 'key' is not found
```

I think finally my config is wrong.

``` yml
aequasi_memcached:
    doctrine:
        metadata:
            cluster: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result:
            cluster: default
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query:
            cluster: default
            entity_manager: default
    clusters:
        default:
            persistent_id: cluster_1
            options:
                connect_timeout: 50
                recv_timeout: 500000
                send_timeout: 500000
                poll_timeout: 50
                retry_timeout: 5
                no_block: true
                server_failure_limit: 7
                tcp_no_delay: true
            keyMap:
                connection: default
    session:
        cluster: default
        prefix: "quotes_"
        ttl: 7200
```
