### ISSUE TITLE
InvalidConfigurationException: Unrecognized options "prefix" under "memcached.doctrine.result"

### ISSUE THREAD

**Issue by FrancisVarga** [aequasi/memcached-bundle#5]
Hello again, :)
Config:

```
aequasi_memcached:
    doctrine:
        metadata:
            cluster: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result:
            cluster: default
            entity_manager: [default, read]  # you may specify multiple entity_managers
            prefix: "result_"
        query:
            cluster: default
            entity_manager: default
    clusters:
        default:
            hosts: %memcached.hosts%
            persistent_id: cluster_1
            options:
                connect_timeout: 50
                recv_timeout: 500000
                send_timeout: 500000
                poll_timeout: 50
                retry_timeout: 5
                no_block: true
                server_failure_limit: 7
                tcp_no_delay: true
            keyMap:
                connection: default
    session:
        cluster: default
        prefix: "quotes_"
        ttl: 7200
```
